/* auto-generated by NAPI-RS-OHOS */
/* eslint-disable */
export function safeRequest(url: string, headers: Record<string, string>, method: string, body: string, ignoreSsl: boolean): Promise<string>

